services:

  mysql:
    image: mysql:8.4
    container_name: ridetap-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123
      MYSQL_DATABASE: ridetap_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: ridetap-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: ridetap-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ridetap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ridetap-app
    restart: unless-stopped
    depends_on:
      - mysql
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ridetap_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: mysql_username
      SPRING_DATASOURCE_PASSWORD: mysql_password

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      JWT_SECRET: jwt_secret

      GEMINI_API_KEY: gemini_api_key

      MAIL_USERNAME: email_id
      MAIL_PASSWORD: email_app_password


volumes:
  mysql_data: